version: '3.8'

services:
  google-trends:
    image: google-trends
    ports:
      - "7863:7863"
    volumes:
      - D:/Service/docker-volumes/google-trends/logs:/app/logs
      - D:/Service/docker-volumes/google-trends/tasks:/app/tasks
    environment:
      - HEADLESS=true
      - LOG_LEVEL=INFO
      - PLATFORM=server
      - PROXY_URL=http://192.168.31.85:10809
    restart: always
    command: python main.py --port 7863