version: '3.8'

services:
  google-trends:
    image: google-trends
    ports:
      - "7863:7861"
    volumes:
      - D:/Service/docker-volumes/google-trends/logs:/app/logs
      - D:/Service/docker-volumes/google-trends/tasks:/assets/tasks
      - D:/Service/docker-volumes/google-trends/zip:/assets/zip
    environment:
      - ZIP_DIR=/assets/zip
      - TASK_DIR=/assets/tasks
      - LOCAL_LLM_URL=http://192.168.31.85:11434/api/generate
      - CLOUD_API_KEY=
      - LOCAL_MODEL_NAME=gemma3
      - LOG_LEVEL=INFO
      - PLATFORM=server
      - PROXY_URL=http://192.168.31.85:10811
      - SERPER_API_KEY=
    restart: always
    command: python webui.py --port 7861