version: '3.8'

services:
  google-trends:
    image: google-trends
    ports:
      - "7863:7861"
    volumes:
      - D:/Service/docker-volumes/google-trends/logs:/app/logs
      - D:/Service/docker-volumes/google-trends/tasks:/app/tasks
    environment:
      - ZIP_DIR=/assets/zip
      - TASK_DIR=/assets/tasks
      - LLM_URL=http://192.168.31.85:11434/api/generate
      - API_KEY=sk-xprtiszdkkdaadtwsilquhcxyjaguhjfrtfncpzlgckhwaje
      - MODEL_NAME=gemma3
      - LOG_LEVEL=INFO
      - PLATFORM=server
      - PROXY_URL=http://192.168.31.85:10811
    restart: always
    command: python main.py --port 7861